import { firestoreService } from './firestoreService';

export interface SeedVoter {
  id: string;
  name: string;
  phone: string;
  cpf?: string;
  rg?: string;
  titulo?: string;
  address: string;
  bairro: string;
  municipio: string;
  zona: string;
  secao: string;
  localVotacao: string;
  leaderId: string;
  leaderName: string;
  leaderEmail: string;
  team: string;
  teamName: string;
  teamId: string;
  coordinatorId: string;
  regionalCoordId: string;
  regionalCoordEmail: string;
  votingIntent: 'Apoiador Convicto' | 'Simpatizante' | 'Indeciso' | 'Apoia Adversário';
  status: 'confirmado' | 'potencial' | 'agendado';
  voted: boolean;
  notes?: string;
  createdAt: number;
  registeredBy: string;
  createdBy: string;
}

export const SEED_REGIONAL_COORDINATORS = [
  {
    id: 'reg_antonio_norte',
    name: 'Antônio Coordenador Regional Norte',
    email: 'antonio.regional@campanha.com',
    phone: '(95) 99111-2233',
    region: 'REGIÃO 1 - NORTE',
    subLocations: 'Boa Vista, Pacaraima, Amajari, Uiramutã, Normandia',
    targetVoters: 2500,
    role: 'coordenador_regional',
    tempPassword: '123',
    coordinatorId: 'geral',
    createdAt: Date.now() - 86400000 * 30
  },
  {
    id: 'reg_joao_sul',
    name: 'João Coordenador Regional Sul',
    email: 'joao.regional@campanha.com',
    phone: '(95) 99222-3344',
    region: 'REGIÃO 2 - SUL',
    subLocations: 'Caracaraí, Rorainópolis, São Luiz, São João da Baliza, Caroebe',
    targetVoters: 2000,
    role: 'coordenador_regional',
    tempPassword: '123',
    coordinatorId: 'geral',
    createdAt: Date.now() - 86400000 * 28
  },
  {
    id: 'reg_marcos_central',
    name: 'Marcos Coordenador Regional Central',
    email: 'marcos.central@campanha.com',
    phone: '(95) 99333-4455',
    region: 'REGIÃO 3 - CENTRAL',
    subLocations: 'Alto Alegre, Cantá, Mucajaí, Iracema, Bonfim',
    targetVoters: 1800,
    role: 'coordenador_regional',
    tempPassword: '123',
    coordinatorId: 'geral',
    createdAt: Date.now() - 86400000 * 25
  }
];

export const SEED_TEAMS = [
  {
    id: 'equipe_pintolandia',
    name: 'Equipe 01 - Pintolândia (Boa Vista)',
    leader: 'Marcos Silva (Líder Pintolândia)',
    leaderEmail: 'marcos.lider@campanha.com',
    leaderPhone: '(95) 99182-1010',
    leaderAddress: 'Rua Pedro Aldemar, 45 - Pintolândia, Boa Vista - RR',
    region: 'REGIÃO 1 - NORTE',
    regionalCoordId: 'reg_antonio_norte',
    regionalCoordEmail: 'antonio.regional@campanha.com',
    neighborhoods: 'Pintolândia, Raiar do Sol, Laura Moreira, Santa Luzia',
    targetVoters: 600,
    allocated: 1200,
    spent: 850,
    contacts: 18,
    demands: 3,
    fuel: 15,
    tempPassword: '123',
    coordinatorId: 'geral',
    createdAt: Date.now() - 86400000 * 20
  },
  {
    id: 'equipe_centro_bv',
    name: 'Equipe 02 - Centro & União (Boa Vista)',
    leader: 'Roberto Carlos (Líder Centro)',
    leaderEmail: 'roberto.lider@campanha.com',
    leaderPhone: '(95) 99182-2020',
    leaderAddress: 'Av. Jaime Brasil, 120 - Centro, Boa Vista - RR',
    region: 'REGIÃO 1 - NORTE',
    regionalCoordId: 'reg_antonio_norte',
    regionalCoordEmail: 'antonio.regional@campanha.com',
    neighborhoods: 'Centro, União, Mecejana, São Francisco, Calungá',
    targetVoters: 500,
    allocated: 1000,
    spent: 600,
    contacts: 14,
    demands: 2,
    fuel: 10,
    tempPassword: '123',
    coordinatorId: 'geral',
    createdAt: Date.now() - 86400000 * 18
  },
  {
    id: 'equipe_caracarai',
    name: 'Equipe 03 - Caracaraí Mobilização',
    leader: 'Sueli Mendes (Líder Caracaraí)',
    leaderEmail: 'sueli.lider@campanha.com',
    leaderPhone: '(95) 99282-3030',
    leaderAddress: 'Rua Dr. Zanny, 310 - Centro, Caracaraí - RR',
    region: 'REGIÃO 2 - SUL',
    regionalCoordId: 'reg_joao_sul',
    regionalCoordEmail: 'joao.regional@campanha.com',
    neighborhoods: 'Centro, Livramento, São José Operário, Nossa Senhora do Livramento',
    targetVoters: 400,
    allocated: 800,
    spent: 500,
    contacts: 12,
    demands: 1,
    fuel: 12,
    tempPassword: '123',
    coordinatorId: 'geral',
    createdAt: Date.now() - 86400000 * 15
  },
  {
    id: 'equipe_rorainopolis',
    name: 'Equipe 04 - Rorainópolis Centro & Sul',
    leader: 'Paulo César (Líder Rorainópolis)',
    leaderEmail: 'paulo.lider@campanha.com',
    leaderPhone: '(95) 99282-4040',
    leaderAddress: 'Av. Dra. Yane, 88 - Centro, Rorainópolis - RR',
    region: 'REGIÃO 2 - SUL',
    regionalCoordId: 'reg_joao_sul',
    regionalCoordEmail: 'joao.regional@campanha.com',
    neighborhoods: 'Centro, Campinarana, Parque das Orquídeas, Suely Campos',
    targetVoters: 450,
    allocated: 900,
    spent: 700,
    contacts: 15,
    demands: 4,
    fuel: 14,
    tempPassword: '123',
    coordinatorId: 'geral',
    createdAt: Date.now() - 86400000 * 14
  },
  {
    id: 'equipe_canta',
    name: 'Equipe 05 - Cantá & Região',
    leader: 'Cláudia Vieira (Líder Cantá)',
    leaderEmail: 'claudia.lider@campanha.com',
    leaderPhone: '(95) 99382-5050',
    leaderAddress: 'Rua Principal, s/n - Sede, Cantá - RR',
    region: 'REGIÃO 3 - CENTRAL',
    regionalCoordId: 'reg_marcos_central',
    regionalCoordEmail: 'marcos.central@campanha.com',
    neighborhoods: 'Sede Cantá, Vila de Taboca, Felix Pinto, Malacacheta',
    targetVoters: 350,
    allocated: 700,
    spent: 400,
    contacts: 10,
    demands: 2,
    fuel: 8,
    tempPassword: '123',
    coordinatorId: 'geral',
    createdAt: Date.now() - 86400000 * 12
  },
  {
    id: 'equipe_mucajai',
    name: 'Equipe 06 - Mucajaí Campo',
    leader: 'Gilson Ramos (Líder Mucajaí)',
    leaderEmail: 'gilson.lider@campanha.com',
    leaderPhone: '(95) 99382-6060',
    leaderAddress: 'Av. Pe. Ricardo, 204 - Centro, Mucajaí - RR',
    region: 'REGIÃO 3 - CENTRAL',
    regionalCoordId: 'reg_marcos_central',
    regionalCoordEmail: 'marcos.central@campanha.com',
    neighborhoods: 'Centro, Tamandaré, Vila Samaúma, Apiaú',
    targetVoters: 380,
    allocated: 750,
    spent: 450,
    contacts: 11,
    demands: 3,
    fuel: 9,
    tempPassword: '123',
    coordinatorId: 'geral',
    createdAt: Date.now() - 86400000 * 10
  },
  {
    id: 'equipe_pacaraima',
    name: 'Equipe 07 - Pacaraima Fronteira',
    leader: 'Vanderlei Silva (Líder Pacaraima)',
    leaderEmail: 'vanderlei.lider@campanha.com',
    leaderPhone: '(95) 99182-7070',
    leaderAddress: 'Rua Guiana, 15 - Pacaraima - RR',
    region: 'REGIÃO 1 - NORTE',
    regionalCoordId: 'reg_antonio_norte',
    regionalCoordEmail: 'antonio.regional@campanha.com',
    neighborhoods: 'Sede Pacaraima, Suapi, Vila Surumu',
    targetVoters: 300,
    allocated: 600,
    spent: 350,
    contacts: 9,
    demands: 1,
    fuel: 7,
    tempPassword: '123',
    coordinatorId: 'geral',
    createdAt: Date.now() - 86400000 * 8
  }
];

export const SEED_VOTERS: SeedVoter[] = [
  // --- BOA VISTA (Pintolândia) ---
  {
    id: 'voter_bv_1',
    name: 'Maria das Graças Silva',
    phone: '(95) 99182-1101',
    cpf: '321.456.789-01',
    address: 'Rua Pedro Aldemar, 120',
    bairro: 'Pintolândia',
    municipio: 'Boa Vista',
    zona: '001',
    secao: '0142',
    localVotacao: 'Escola Estadual Mário David Andreazza',
    leaderId: 'equipe_pintolandia',
    leaderName: 'Marcos Silva (Líder Pintolândia)',
    leaderEmail: 'marcos.lider@campanha.com',
    team: 'Equipe 01 - Pintolândia (Boa Vista)',
    teamName: 'Equipe 01 - Pintolândia (Boa Vista)',
    teamId: 'equipe_pintolandia',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_antonio_norte',
    regionalCoordEmail: 'antonio.regional@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Apoiadora forte do bairro, mobiliza familiares no Pintolândia.',
    createdAt: Date.now() - 86400000 * 19,
    registeredBy: 'marcos.lider@campanha.com',
    createdBy: 'marcos.lider@campanha.com'
  },
  {
    id: 'voter_bv_2',
    name: 'João Pedro Oliveira Santos',
    phone: '(95) 99182-1102',
    cpf: '432.567.890-12',
    address: 'Av. Nazareno Filgueiras, 850',
    bairro: 'Pintolândia',
    municipio: 'Boa Vista',
    zona: '001',
    secao: '0145',
    localVotacao: 'Escola Estadual Mário David Andreazza',
    leaderId: 'equipe_pintolandia',
    leaderName: 'Marcos Silva (Líder Pintolândia)',
    leaderEmail: 'marcos.lider@campanha.com',
    team: 'Equipe 01 - Pintolândia (Boa Vista)',
    teamName: 'Equipe 01 - Pintolândia (Boa Vista)',
    teamId: 'equipe_pintolandia',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_antonio_norte',
    regionalCoordEmail: 'antonio.regional@campanha.com',
    votingIntent: 'Simpatizante',
    status: 'potencial',
    voted: false,
    notes: 'Pediu material impresso e adesivo para o carro.',
    createdAt: Date.now() - 86400000 * 18,
    registeredBy: 'marcos.lider@campanha.com',
    createdBy: 'marcos.lider@campanha.com'
  },
  {
    id: 'voter_bv_3',
    name: 'Francisca Souza Lima',
    phone: '(95) 99182-1103',
    cpf: '543.678.901-23',
    address: 'Rua S-14, 45',
    bairro: 'Raiar do Sol',
    municipio: 'Boa Vista',
    zona: '001',
    secao: '0201',
    localVotacao: 'Escola Municipal Valdemarina Normando Martins',
    leaderId: 'equipe_pintolandia',
    leaderName: 'Marcos Silva (Líder Pintolândia)',
    leaderEmail: 'marcos.lider@campanha.com',
    team: 'Equipe 01 - Pintolândia (Boa Vista)',
    teamName: 'Equipe 01 - Pintolândia (Boa Vista)',
    teamId: 'equipe_pintolandia',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_antonio_norte',
    regionalCoordEmail: 'antonio.regional@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Liderança comunitária da rua S-14.',
    createdAt: Date.now() - 86400000 * 17,
    registeredBy: 'marcos.lider@campanha.com',
    createdBy: 'marcos.lider@campanha.com'
  },
  {
    id: 'voter_bv_4',
    name: 'Carlos Eduardo Rodrigues',
    phone: '(95) 99182-1104',
    cpf: '654.789.012-34',
    address: 'Rua N-11, 210',
    bairro: 'Laura Moreira',
    municipio: 'Boa Vista',
    zona: '001',
    secao: '0215',
    localVotacao: 'Escola Municipal Raimundo Eloy Gomes',
    leaderId: 'equipe_pintolandia',
    leaderName: 'Marcos Silva (Líder Pintolândia)',
    leaderEmail: 'marcos.lider@campanha.com',
    team: 'Equipe 01 - Pintolândia (Boa Vista)',
    teamName: 'Equipe 01 - Pintolândia (Boa Vista)',
    teamId: 'equipe_pintolandia',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_antonio_norte',
    regionalCoordEmail: 'antonio.regional@campanha.com',
    votingIntent: 'Indeciso',
    status: 'potencial',
    voted: false,
    notes: 'Solicitou visita da liderança regional.',
    createdAt: Date.now() - 86400000 * 16,
    registeredBy: 'marcos.lider@campanha.com',
    createdBy: 'marcos.lider@campanha.com'
  },

  // --- BOA VISTA (Centro & União) ---
  {
    id: 'voter_bv_5',
    name: 'Ana Clara Barbosa',
    phone: '(95) 99182-2201',
    cpf: '765.890.123-45',
    address: 'Av. Jaime Brasil, 340',
    bairro: 'Centro',
    municipio: 'Boa Vista',
    zona: '005',
    secao: '0012',
    localVotacao: 'Escola Estadual Lobo D\'Almada',
    leaderId: 'equipe_centro_bv',
    leaderName: 'Roberto Carlos (Líder Centro)',
    leaderEmail: 'roberto.lider@campanha.com',
    team: 'Equipe 02 - Centro & União (Boa Vista)',
    teamName: 'Equipe 02 - Centro & União (Boa Vista)',
    teamId: 'equipe_centro_bv',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_antonio_norte',
    regionalCoordEmail: 'antonio.regional@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Comerciante do Centro, apoia integralmente.',
    createdAt: Date.now() - 86400000 * 15,
    registeredBy: 'roberto.lider@campanha.com',
    createdBy: 'roberto.lider@campanha.com'
  },
  {
    id: 'voter_bv_6',
    name: 'Raimundo Nonato Pereira',
    phone: '(95) 99182-2202',
    cpf: '876.901.234-56',
    address: 'Rua Cecília Brasil, 180',
    bairro: 'União',
    municipio: 'Boa Vista',
    zona: '005',
    secao: '0034',
    localVotacao: 'Escola Estadual Monteiro Lobato',
    leaderId: 'equipe_centro_bv',
    leaderName: 'Roberto Carlos (Líder Centro)',
    leaderEmail: 'roberto.lider@campanha.com',
    team: 'Equipe 02 - Centro & União (Boa Vista)',
    teamName: 'Equipe 02 - Centro & União (Boa Vista)',
    teamId: 'equipe_centro_bv',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_antonio_norte',
    regionalCoordEmail: 'antonio.regional@campanha.com',
    votingIntent: 'Simpatizante',
    status: 'confirmado',
    voted: false,
    notes: 'Gostou das propostas para saúde e infraestrutura.',
    createdAt: Date.now() - 86400000 * 14,
    registeredBy: 'roberto.lider@campanha.com',
    createdBy: 'roberto.lider@campanha.com'
  },
  {
    id: 'voter_bv_7',
    name: 'Juliana Rodrigues Costa',
    phone: '(95) 99182-2203',
    cpf: '987.012.345-67',
    address: 'Rua Bento Brasil, 520',
    bairro: 'São Francisco',
    municipio: 'Boa Vista',
    zona: '005',
    secao: '0050',
    localVotacao: 'Escola Estadual Euclides da Cunha',
    leaderId: 'equipe_centro_bv',
    leaderName: 'Roberto Carlos (Líder Centro)',
    leaderEmail: 'roberto.lider@campanha.com',
    team: 'Equipe 02 - Centro & União (Boa Vista)',
    teamName: 'Equipe 02 - Centro & União (Boa Vista)',
    teamId: 'equipe_centro_bv',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_antonio_norte',
    regionalCoordEmail: 'antonio.regional@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Voluntária ativa em reuniões de bairro.',
    createdAt: Date.now() - 86400000 * 13,
    registeredBy: 'roberto.lider@campanha.com',
    createdBy: 'roberto.lider@campanha.com'
  },

  // --- CARACARAÍ ---
  {
    id: 'voter_car_1',
    name: 'Manoel Messias Ribeiro',
    phone: '(95) 99282-3301',
    cpf: '123.890.456-78',
    address: 'Rua Dr. Zanny, 140',
    bairro: 'Centro',
    municipio: 'Caracaraí',
    zona: '002',
    secao: '0005',
    localVotacao: 'Escola Estadual José de Alencar',
    leaderId: 'equipe_caracarai',
    leaderName: 'Sueli Mendes (Líder Caracaraí)',
    leaderEmail: 'sueli.lider@campanha.com',
    team: 'Equipe 03 - Caracaraí Mobilização',
    teamName: 'Equipe 03 - Caracaraí Mobilização',
    teamId: 'equipe_caracarai',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_joao_sul',
    regionalCoordEmail: 'joao.regional@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Articulador local de pescadores em Caracaraí.',
    createdAt: Date.now() - 86400000 * 13,
    registeredBy: 'sueli.lider@campanha.com',
    createdBy: 'sueli.lider@campanha.com'
  },
  {
    id: 'voter_car_2',
    name: 'Sônia Maria Barbosa',
    phone: '(95) 99282-3302',
    cpf: '234.901.567-89',
    address: 'Av. Presidente Kennedy, 410',
    bairro: 'Livramento',
    municipio: 'Caracaraí',
    zona: '002',
    secao: '0018',
    localVotacao: 'Escola Municipal Presidente Castelo Branco',
    leaderId: 'equipe_caracarai',
    leaderName: 'Sueli Mendes (Líder Caracaraí)',
    leaderEmail: 'sueli.lider@campanha.com',
    team: 'Equipe 03 - Caracaraí Mobilização',
    teamName: 'Equipe 03 - Caracaraí Mobilização',
    teamId: 'equipe_caracarai',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_joao_sul',
    regionalCoordEmail: 'joao.regional@campanha.com',
    votingIntent: 'Simpatizante',
    status: 'confirmado',
    voted: false,
    notes: 'Família tradicional da cidade apoiando a chapa.',
    createdAt: Date.now() - 86400000 * 12,
    registeredBy: 'sueli.lider@campanha.com',
    createdBy: 'sueli.lider@campanha.com'
  },
  {
    id: 'voter_car_3',
    name: 'Gerson Fernandes Castro',
    phone: '(95) 99282-3303',
    cpf: '345.012.678-90',
    address: 'Rua São José, 88',
    bairro: 'São José Operário',
    municipio: 'Caracaraí',
    zona: '002',
    secao: '0022',
    localVotacao: 'Escola Municipal Presidente Castelo Branco',
    leaderId: 'equipe_caracarai',
    leaderName: 'Sueli Mendes (Líder Caracaraí)',
    leaderEmail: 'sueli.lider@campanha.com',
    team: 'Equipe 03 - Caracaraí Mobilização',
    teamName: 'Equipe 03 - Caracaraí Mobilização',
    teamId: 'equipe_caracarai',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_joao_sul',
    regionalCoordEmail: 'joao.regional@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Representante de bairro em Caracaraí.',
    createdAt: Date.now() - 86400000 * 11,
    registeredBy: 'sueli.lider@campanha.com',
    createdBy: 'sueli.lider@campanha.com'
  },

  // --- RORAINÓPOLIS ---
  {
    id: 'voter_ror_1',
    name: 'Antônio Carlos Ferreira',
    phone: '(95) 99282-4401',
    cpf: '456.123.789-01',
    address: 'Av. Dra. Yane, 310',
    bairro: 'Centro',
    municipio: 'Rorainópolis',
    zona: '008',
    secao: '0010',
    localVotacao: 'Escola Estadual José de Alencar (Rorainópolis)',
    leaderId: 'equipe_rorainopolis',
    leaderName: 'Paulo César (Líder Rorainópolis)',
    leaderEmail: 'paulo.lider@campanha.com',
    team: 'Equipe 04 - Rorainópolis Centro & Sul',
    teamName: 'Equipe 04 - Rorainópolis Centro & Sul',
    teamId: 'equipe_rorainopolis',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_joao_sul',
    regionalCoordEmail: 'joao.regional@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Mobilizador do comércio local de Rorainópolis.',
    createdAt: Date.now() - 86400000 * 11,
    registeredBy: 'paulo.lider@campanha.com',
    createdBy: 'paulo.lider@campanha.com'
  },
  {
    id: 'voter_ror_2',
    name: 'Valéria Cristina Nascimento',
    phone: '(95) 99282-4402',
    cpf: '567.234.890-12',
    address: 'Rua das Palmeiras, 95',
    bairro: 'Campinarana',
    municipio: 'Rorainópolis',
    zona: '008',
    secao: '0025',
    localVotacao: 'Escola Municipal Antônio Vieira de Melo',
    leaderId: 'equipe_rorainopolis',
    leaderName: 'Paulo César (Líder Rorainópolis)',
    leaderEmail: 'paulo.lider@campanha.com',
    team: 'Equipe 04 - Rorainópolis Centro & Sul',
    teamName: 'Equipe 04 - Rorainópolis Centro & Sul',
    teamId: 'equipe_rorainopolis',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_joao_sul',
    regionalCoordEmail: 'joao.regional@campanha.com',
    votingIntent: 'Simpatizante',
    status: 'confirmado',
    voted: false,
    notes: 'Professora atuante em Rorainópolis.',
    createdAt: Date.now() - 86400000 * 10,
    registeredBy: 'paulo.lider@campanha.com',
    createdBy: 'paulo.lider@campanha.com'
  },
  {
    id: 'voter_ror_3',
    name: 'José Luiz Martins',
    phone: '(95) 99282-4403',
    cpf: '678.345.901-23',
    address: 'Rua dos Pinheiros, 14',
    bairro: 'Parque das Orquídeas',
    municipio: 'Rorainópolis',
    zona: '008',
    secao: '0032',
    localVotacao: 'Escola Municipal Antônio Vieira de Melo',
    leaderId: 'equipe_rorainopolis',
    leaderName: 'Paulo César (Líder Rorainópolis)',
    leaderEmail: 'paulo.lider@campanha.com',
    team: 'Equipe 04 - Rorainópolis Centro & Sul',
    teamName: 'Equipe 04 - Rorainópolis Centro & Sul',
    teamId: 'equipe_rorainopolis',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_joao_sul',
    regionalCoordEmail: 'joao.regional@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Organiza reunião de moradores no Parque das Orquídeas.',
    createdAt: Date.now() - 86400000 * 9,
    registeredBy: 'paulo.lider@campanha.com',
    createdBy: 'paulo.lider@campanha.com'
  },

  // --- CANTÁ ---
  {
    id: 'voter_can_1',
    name: 'Eliane Maria Duarte',
    phone: '(95) 99382-5501',
    cpf: '789.456.012-34',
    address: 'Rua Principal, 40',
    bairro: 'Sede Cantá',
    municipio: 'Cantá',
    zona: '005',
    secao: '0110',
    localVotacao: 'Escola Estadual Tia Geni',
    leaderId: 'equipe_canta',
    leaderName: 'Cláudia Vieira (Líder Cantá)',
    leaderEmail: 'claudia.lider@campanha.com',
    team: 'Equipe 05 - Cantá & Região',
    teamName: 'Equipe 05 - Cantá & Região',
    teamId: 'equipe_canta',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_marcos_central',
    regionalCoordEmail: 'marcos.central@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Liderança rural no Cantá.',
    createdAt: Date.now() - 86400000 * 9,
    registeredBy: 'claudia.lider@campanha.com',
    createdBy: 'claudia.lider@campanha.com'
  },
  {
    id: 'voter_can_2',
    name: 'Sebastião Alencar Filho',
    phone: '(95) 99382-5502',
    cpf: '890.567.123-45',
    address: 'Vila Taboca, Lote 12',
    bairro: 'Vila de Taboca',
    municipio: 'Cantá',
    zona: '005',
    secao: '0118',
    localVotacao: 'Escola Municipal da Vila Taboca',
    leaderId: 'equipe_canta',
    leaderName: 'Cláudia Vieira (Líder Cantá)',
    leaderEmail: 'claudia.lider@campanha.com',
    team: 'Equipe 05 - Cantá & Região',
    teamName: 'Equipe 05 - Cantá & Região',
    teamId: 'equipe_canta',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_marcos_central',
    regionalCoordEmail: 'marcos.central@campanha.com',
    votingIntent: 'Simpatizante',
    status: 'confirmado',
    voted: false,
    notes: 'Produtor da agricultura familiar no Cantá.',
    createdAt: Date.now() - 86400000 * 8,
    registeredBy: 'claudia.lider@campanha.com',
    createdBy: 'claudia.lider@campanha.com'
  },

  // --- MUCAJAÍ ---
  {
    id: 'voter_muc_1',
    name: 'Benedito da Silva Ramos',
    phone: '(95) 99382-6601',
    cpf: '901.678.234-56',
    address: 'Av. Pe. Ricardo, 105',
    bairro: 'Centro',
    municipio: 'Mucajaí',
    zona: '006',
    secao: '0015',
    localVotacao: 'Escola Estadual Nossa Senhora da Penha',
    leaderId: 'equipe_mucajai',
    leaderName: 'Gilson Ramos (Líder Mucajaí)',
    leaderEmail: 'gilson.lider@campanha.com',
    team: 'Equipe 06 - Mucajaí Campo',
    teamName: 'Equipe 06 - Mucajaí Campo',
    teamId: 'equipe_mucajai',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_marcos_central',
    regionalCoordEmail: 'marcos.central@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Empresário do setor de transportes em Mucajaí.',
    createdAt: Date.now() - 86400000 * 7,
    registeredBy: 'gilson.lider@campanha.com',
    createdBy: 'gilson.lider@campanha.com'
  },
  {
    id: 'voter_muc_2',
    name: 'Luciana Mendonça Xavier',
    phone: '(95) 99382-6602',
    cpf: '012.789.345-67',
    address: 'Rua Tamandaré, 77',
    bairro: 'Tamandaré',
    municipio: 'Mucajaí',
    zona: '006',
    secao: '0028',
    localVotacao: 'Escola Municipal Mário Homem de Mello',
    leaderId: 'equipe_mucajai',
    leaderName: 'Gilson Ramos (Líder Mucajaí)',
    leaderEmail: 'gilson.lider@campanha.com',
    team: 'Equipe 06 - Mucajaí Campo',
    teamName: 'Equipe 06 - Mucajaí Campo',
    teamId: 'equipe_mucajai',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_marcos_central',
    regionalCoordEmail: 'marcos.central@campanha.com',
    votingIntent: 'Simpatizante',
    status: 'confirmado',
    voted: false,
    notes: 'Mobilizadora de saúde comunitária.',
    createdAt: Date.now() - 86400000 * 6,
    registeredBy: 'gilson.lider@campanha.com',
    createdBy: 'gilson.lider@campanha.com'
  },

  // --- PACARAIMA ---
  {
    id: 'voter_pac_1',
    name: 'Diego Armando Souza',
    phone: '(95) 99182-7701',
    cpf: '123.890.123-89',
    address: 'Rua Guiana, 42',
    bairro: 'Sede Pacaraima',
    municipio: 'Pacaraima',
    zona: '007',
    secao: '0008',
    localVotacao: 'Escola Estadual Padre José Monticone',
    leaderId: 'equipe_pacaraima',
    leaderName: 'Vanderlei Silva (Líder Pacaraima)',
    leaderEmail: 'vanderlei.lider@campanha.com',
    team: 'Equipe 07 - Pacaraima Fronteira',
    teamName: 'Equipe 07 - Pacaraima Fronteira',
    teamId: 'equipe_pacaraima',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_antonio_norte',
    regionalCoordEmail: 'antonio.regional@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Comerciante de Pacaraima atuante na fronteira.',
    createdAt: Date.now() - 86400000 * 5,
    registeredBy: 'vanderlei.lider@campanha.com',
    createdBy: 'vanderlei.lider@campanha.com'
  },

  // --- ALTO ALEGRE ---
  {
    id: 'voter_aal_1',
    name: 'Renata Albuquerque Prado',
    phone: '(95) 99382-8801',
    cpf: '234.901.234-90',
    address: 'Rua da Amizade, 12',
    bairro: 'Centro',
    municipio: 'Alto Alegre',
    zona: '003',
    secao: '0004',
    localVotacao: 'Escola Estadual Sadoc Pereira',
    leaderId: 'equipe_mucajai',
    leaderName: 'Gilson Ramos (Líder Mucajaí)',
    leaderEmail: 'gilson.lider@campanha.com',
    team: 'Equipe 06 - Mucajaí Campo',
    teamName: 'Equipe 06 - Mucajaí Campo',
    teamId: 'equipe_mucajai',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_marcos_central',
    regionalCoordEmail: 'marcos.central@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Liderança local em Alto Alegre.',
    createdAt: Date.now() - 86400000 * 4,
    registeredBy: 'gilson.lider@campanha.com',
    createdBy: 'gilson.lider@campanha.com'
  },

  // --- SÃO JOÃO DA BALIZA ---
  {
    id: 'voter_sjb_1',
    name: 'Ezequiel Viana Santos',
    phone: '(95) 99282-9901',
    cpf: '345.012.345-01',
    address: 'Av. Brasil, 230',
    bairro: 'Centro',
    municipio: 'São João da Baliza',
    zona: '004',
    secao: '0002',
    localVotacao: 'Escola Estadual Francisco Ricardo',
    leaderId: 'equipe_rorainopolis',
    leaderName: 'Paulo César (Líder Rorainópolis)',
    leaderEmail: 'paulo.lider@campanha.com',
    team: 'Equipe 04 - Rorainópolis Centro & Sul',
    teamName: 'Equipe 04 - Rorainópolis Centro & Sul',
    teamId: 'equipe_rorainopolis',
    coordinatorId: 'geral',
    regionalCoordId: 'reg_joao_sul',
    regionalCoordEmail: 'joao.regional@campanha.com',
    votingIntent: 'Apoiador Convicto',
    status: 'confirmado',
    voted: false,
    notes: 'Produtor rural de São João da Baliza.',
    createdAt: Date.now() - 86400000 * 3,
    registeredBy: 'paulo.lider@campanha.com',
    createdBy: 'paulo.lider@campanha.com'
  }
];

let seedInProgress = false;

export async function ensureSeedCampaignData(): Promise<void> {
  if (seedInProgress) return;
  seedInProgress = true;

  try {
    const existingVoters = await firestoreService.getCollection<any>('voters');
    
    // 1. Seed Voters if none or less than 5 voters exist
    if (!existingVoters || existingVoters.length < 5) {
      console.log("🌱 Alimentando base de eleitores cadastrados por líderes de equipe...");
      for (const voter of SEED_VOTERS) {
        await firestoreService.setDocument('voters', voter.id, voter, true);
      }
    }

    // 2. Seed Regional Coordinators if missing
    const existingRegionals = await firestoreService.getCollection<any>('regional_coordinators');
    if (!existingRegionals || existingRegionals.length < 2) {
      console.log("🌱 Alimentando coordenadores regionais...");
      for (const reg of SEED_REGIONAL_COORDINATORS) {
        await firestoreService.setDocument('regional_coordinators', reg.id, reg, true);
      }
    }

    // 3. Seed Teams if missing
    const existingTeams = await firestoreService.getCollection<any>('teams');
    if (!existingTeams || existingTeams.length < 3) {
      console.log("🌱 Alimentando equipes e líderes de campo...");
      for (const team of SEED_TEAMS) {
        await firestoreService.setDocument('teams', team.id, team, true);
      }
    }
  } catch (err) {
    console.warn("Erro ao alimentar dados iniciais da campanha:", err);
  } finally {
    seedInProgress = false;
  }
}
